title: Jean-Baptiste BAITAIRIAN
email: jean-baptiste.baitairian@inria.fr
description: >-
  Jean-Baptiste BAITAIRIAN's website.
baseurl: ""
url: "jeanbaptistebaitairian.github.io"
github_username: "jeanbaptistebaitairian"
linkedin_username: "jean-baptiste-baitairian-90a9b4192"

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
#LeNPaul/academic

name: Jean-Baptiste BAITAIRIAN's website.

exclude:
  - tmp/
  - vendor/
  - Gemfile
  - Gemfile.lock
