title: Jean-Baptiste BAITAIRIAN
email: jean-baptiste.baitairian@inria.fr
description: >-
  Jean-Baptiste BAITAIRIAN's website.
baseurl: ""
url: "jeanbaptistebaitairian.github.io"
github_username: "jeanbaptistebaitairian"

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

name: Jean-Baptiste BAITAIRIAN's website.

exclude:
  - tmp/
  - vendor/
  - Gemfile
  - Gemfile.lock
